services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/load_hnm.sql:/docker-entrypoint-initdb.d/02_load.sql
      - ./data/raw:/data/hnm:ro
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"

  image-service:
    build:
      context: ./services/image-service
    environment:
      IMAGES_DIR: /data/images
    volumes:
      - ./data/raw/hnm/images:/data/images:ro
    ports:
      - "8001:8000"

  vton-service:
    build: ./services/vton-services
    ports:
      - "8002:8000"
    environment:
      HF_TOKEN: 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

  kg-service:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password123
    ports:
      - "7474:7474" # Web Browser UI
      - "7687:7687" # Python connection port
    volumes:
      - ./data/neo4j_data:/data
